# This is a basic workflow to help you get started with Actions
name: Deploy Azure Resources with Terraform
on:
  workflow_dispatch:
 
 
jobs:
  terraform:
    runs-on: ubuntu-latest
    timeout-minutes: 180

 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
 

      - name: Install Az PowerShell Module
        shell: pwsh
        run: |
          Install-Module -Name Az -Force -Scope CurrentUser -Repository PSGallery
          Import-Module Az

      - name: Azure Login using Service Principal
        shell: pwsh
        run: |
          $clientId = "${{ secrets.CLIENT_ID }}"
          $clientSecret = "${{ secrets.CLIENT_SECRET }}"
          $tenantId = "${{ secrets.TENANT_ID }}"
          $subscriptionId = "${{ secrets.SUBSCRIPTION_ID }}"
          Connect-AzAccount -ServicePrincipal -Tenant $tenantId -Credential (New-Object System.Management.Automation.PSCredential($clientId, (ConvertTo-SecureString $clientSecret -AsPlainText -Force)))
          Set-AzContext -SubscriptionId $subscriptionId
        

      # - name: Run PowerShell Script
      #   shell: pwsh
      #   run: | 
      #     ./create_rg.ps1
      
      #   env:
      #     AZURE_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      #     AZURE_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      #     AZURE_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      #     AZURE_TENANT_ID: ${{ secrets.TENANT_ID }} 

      - name: Terraform Plan
        run: |
          terraform init
          terraform plan
        env:
          ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.TENANT_ID }}

      - name: Terraform Init and Apply
        run: |
          terraform init
          terraform apply -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.TENANT_ID }}